### ISSUE TITLE
Fix `webflux-netty` smoke test 

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-checkpoint-restore-smoke-tests#14]
When @violetagg is back, let see what can be made on Netty side to fix [current failure](https://ci.spring.io/teams/spring-checkpoint-restore-smoke-tests/pipelines/spring-checkpoint-restore-smoke-tests-3.2.x/jobs/webflux-netty-cr-app-test/builds/1).

Notice on Linux aarch64 running on a Mac M2, it seems to work as expected, so the failure may be architecture specific.

**Comment by violetagg** [comment]
I'll check that

**Comment by violetagg** [comment]
@sdeleuze @wilkinsona We need to dispose `ReactorResourceFactory` on checkpoint and then to recreate it on restore.

https://github.com/spring-projects/spring-boot/blob/018c188cebfda2750d2cc4302343a646105fe0a7/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/netty/NettyReactiveWebServerFactory.java#L163

**Comment by sdeleuze** [comment]
I will do some related test for the HTTP client and provide a feedback since `ReactorResourceFactory` seems to be used on both client and server.

**Comment by sdeleuze** [comment]
So I was able to have `WebClient` with Reactor Netty working with checkpoint/restore after the following modification visible on [this branch](https://github.com/sdeleuze/spring-checkpoint-restore-smoke-tests/tree/webclient-reactor-netty):
 - Make `ReactorClientHttpConnector` lifecycle aware to invoke `destroy()` when stopping the application context and set `loopResources` and `connectionProvider` fields to `null` after invoking `destroy().
 - Make `ReactorClientHttpConnector` lifecycle aware the recreate the `HttpClient` when re-starting the application context.

Looks like modifications would be needed on both Framework and Boot sides to support Reactor Netty, so let's discuss it in an upcoming meeting.

**Comment by sdeleuze** [comment]
I think I have been able to fix that purely on Spring Framework side, will push related-changes after most test and polish.

**Comment by sdeleuze** [comment]
With https://github.com/spring-projects/spring-framework/commit/125b8e741805cc678c427abb248859bd084f0989, `ReactorResourceFactory` is now lifecycle-aware, but unlike what I initially thought, some refinements are likely going to be needed on Spring Boot side, I have created https://github.com/spring-projects/spring-boot/issues/37209 related issue.

**Comment by sdeleuze** [comment]
The related smoke test is now green, thanks @wilkinsona!
